
# API GATEWAY - Common Configuration

spring.application.name=issue-app-gateway

# Active Profile (override via env: SPRING_PROFILES_ACTIVE=prod)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}
