apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      serviceAccountName: issue-app-sa
      containers:
        - name: api-gateway
          image: api-gateway:latest
          ports:
            - containerPort: 8096
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secrets
                  key: JWT_SECRET
            - name: CORS_ALLOWED_ORIGIN
              value: "https://tcmslk.me"
