apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-gateway-secrets
  namespace: issue-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: api-gateway-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: prod/game/jwt
        property: secret
