apiVersion: external-secrets.io/v1  # <--- Changed from v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: issue-app
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: issue-app-sa
      region: us-east-1
      service: SecretsManager