apiVersion: v1
kind: ConfigMap
metadata:
  name: issue-service-config
  namespace: issue-app
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://prod-game-db.xxxxxxxxxxxx.us-east-1.rds.amazonaws.com:3306/game_db"
