apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-app
  labels:
    app: game-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-app
  template:
    metadata:
      labels:
        app: game-app
    spec:
      serviceAccountName: game-app-sa
      # InitContainer handles the dependency check
      initContainers:
        - name: wait-for-db
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z prod-game-db.c8tsk48m85k3.us-east-1.rds.amazonaws.com 3306; do echo waiting for database; sleep 2; done;']
      containers:
        - name: game-app-container
          image: 530352103493.dkr.ecr.us-east-1.amazonaws.com/prod-game-app-repo:adb0593
          # Java entry point
          command: ["java", "-jar", "target/api.jar"]
          ports:
            - containerPort: 8080
          # Probes monitor app health and readiness
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          envFrom:
            - configMapRef:
                name: game-app-config
#          volumeMounts:
#            - name: game-data-volume
#              mountPath: /app/data
#      volumes:
#        - name: game-data-volume
#          persistentVolumeClaim:
#            claimName: game-storage-pvc