apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: game-app-secrets
  namespace: game-app # Matches your namespace
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore # Changed from ClusterSecretStore
  target:
    name: game-app-db-secret # This is the name of the actual K8s secret generated
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: prod/game/db # The name of the secret in AWS Secrets Manager
        property: password


        # force cache reload