apiVersion: external-secrets.io/v1  # <--- Changed from v1beta1
kind: ExternalSecret
metadata:
  name: game-app-secrets
  namespace: game-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: game-app-db-secret
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: prod/game/db
        property: password