apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: game-app

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
#  - pvc.yaml
  - secret-store.yaml
  - external-secret.yaml
  - serviceaccount.yaml
