apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: game-app # Now explicitly inside your namespace
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1 # Change to your AWS region
      # If you are using a specific service account for IAM roles:
      auth:
        jwt:
          serviceAccountRef:
            name: game-app-sa