apiVersion: v1
kind: ServiceAccount
metadata:
  name: game-app-sa
# If you are using AWS IRSA to link an IAM Role, you would add this annotation block:
#   annotations:
#     eks.amazonaws.com/role-arn: arn:aws:iam::YOUR_ACCOUNT_ID:role/YOUR_IAM_ROLE_NAME