apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: api-gateway
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/prod-api-gateway
  newTag: 92d148728bfef883bbb1ae91c41d8e859d3995af
- name: auth-service
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/prod-auth-service
  newTag: 92d148728bfef883bbb1ae91c41d8e859d3995af
- name: frontend-service
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/prod-frontend-service
  newTag: 92d148728bfef883bbb1ae91c41d8e859d3995af
- name: issue-service
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/prod-issue-service
  newTag: 92d148728bfef883bbb1ae91c41d8e859d3995af
