apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: api-gateway
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/prod-api-gateway
  newTag: 9736dc84850b612d58ebcbf38cb2cd430c2b3bb5
- name: auth-service
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/prod-auth-service
  newTag: 9736dc84850b612d58ebcbf38cb2cd430c2b3bb5
- name: frontend-service
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/prod-frontend-service
  newTag: 9736dc84850b612d58ebcbf38cb2cd430c2b3bb5
- name: issue-service
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/prod-issue-service
  newTag: 9736dc84850b612d58ebcbf38cb2cd430c2b3bb5
