apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: api-gateway
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/prod-api-gateway
  newTag: c97e772efe0c85e2d0dc976d47867eb1a6ed2e65
- name: auth-service
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/prod-auth-service
  newTag: c97e772efe0c85e2d0dc976d47867eb1a6ed2e65
- name: frontend-service
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/prod-frontend-service
  newTag: c97e772efe0c85e2d0dc976d47867eb1a6ed2e65
- name: issue-service
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/prod-issue-service
  newTag: c97e772efe0c85e2d0dc976d47867eb1a6ed2e65
