apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-app
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: game-app-container
          image: YOUR_ECR_REPO_URL:latest
##