apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: api-gateway
  newName: api-gateway
  newTag: dev
- name: auth-service
  newName: auth-service
  newTag: dev
- name: issue-service
  newName: issue-service
  newTag: dev
- name: frontend-service
  newName: frontend-service
  newTag: dev
