apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: api-gateway
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/api-gateway
  newTag: staging
- name: auth-service
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/auth-service
  newTag: staging
- name: issue-service
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/issue-service
  newTag: staging
- name: frontend-service
  newName: 530352103493.dkr.ecr.us-east-1.amazonaws.com/frontend-service
  newTag: staging
