name: Terraform Plan

on:
  pull_request:
    branches:
      - prod
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  plan:
    name: Production Plan
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Code Base
        uses: actions/checkout@v4

      - name: 2. Configure AWS Access
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: 3. Initialize Terraform Engine
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: 4. Execute Infrastructure Plan
        run: |
          cd terraform/environments/prod
          terraform init
          terraform plan
        env:
          TF_VAR_db_username: ${{ secrets.DB_USERNAME_PROD }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD_PROD }}
