name: Terraform Apply

on:
  push:
    branches:
      - prod
    paths:
      - 'terraform/**'

jobs:
  apply:
    name: Production Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform -chdir=terraform/environments/prod init

      - name: Terraform Apply
        env:
          TF_VAR_db_username: ${{ secrets.DB_USERNAME_PROD }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD_PROD }}
        run: terraform -chdir=terraform/environments/prod apply -auto-approve

      - name: Automatically Capture and Inject RDS Endpoint
        run: |
          RAW_ENDPOINT=$(terraform -chdir=terraform/environments/prod output -raw database_endpoint)
          CLEAN_HOST=$(echo $RAW_ENDPOINT | cut -d':' -f1)
          
          sed -i "s|RDS_ENDPOINT_PLACEHOLDER|$CLEAN_HOST|g" kubernetes/environments/prod/kustomization.yaml

      - name: Commit and Push Infrastructure Updates
        run: |
          git config --global user.name "GitHub Actions Automation"
          git config --global user.email "actions@github.com"
          git add kubernetes/environments/prod/kustomization.yaml
          git diff-index --quiet HEAD || git commit -m "infra: automatically synced rds endpoint from terraform apply"
          git push
